### ISSUE TITLE
Route less engine mounting with a variable

### ISSUE THREAD

**Issue by ssutar** [ember-engines/ember-engines#117]
`{{mount someVar}}` does not work where `someVar` is a variable with the engine-name

It throws below error:
`Uncaught Error: Assertion Failed: The first argument of {{mount}} must be quoted, e.g. {{mount "chat-engine"}}.`

Not sure if this constraint is by design or an issue

**Comment by mike183** [comment]
Looking at [the code](https://github.com/dgeb/ember-engines/blob/6c330b117b60de4f0cb4f88f3cfba7be0d6d2617/addon/-private/keywords/mount.js#L70-L73), it appears that this behaviour is intentional although I do agree that I think we should be able to pass a variable as the engine name, as long as the value of that variable was a string of course.

**Comment by eccegordo** [comment]
Agreed. I am trying to make a component that dynamically mounts an engine. It would be nice if this was a little more flexible.

What about alternate syntax?

```
{{mountProp someProp}}
```

Also can someone explain why this doesn't work?

```
{{mount (concat "my" "-" "engine")}}
```

**Comment by mike183** [comment]
Just submitted emberjs/ember.js#15015 which will enable routeless engines to be mounted using a bound property.
