### ISSUE TITLE
Issues with lazy engines importing modules in `addon/routes.js`.

### ISSUE THREAD

**Issue by rwjblue** [ember-engines/ember-engines#318]
I have not fully tracked this down, but it appears there is an issue when a lazy engine imports another module in its `addon/routes.js`.  We intend to use `broccoli-dependency-funnel` to ensure that all of the imports are resolved, but for some reason it is not functioning properly.

I haven't spent much time tracking it down, but I did create a failing acceptance test here https://github.com/ember-engines/engine-testing/pull/9 for anyone that wants to dig in...

**Comment by rwjblue** [comment]
Did some quick review of this, and it seems related to the recent change to have `Addon#treeForAddon` and `Addon#compileAddon` return fully transpiled output. Since it is returning modules that are already `DependencyFunnel` cannot properly traverse the imports.

**Comment by trentmwillis** [comment]
Hmm, that seems reasonable. I remember seeing at least one instance where the `DependencyFunnel` was (I thought) already being used on transpiled output, prior to my refactoring.

Regardless, we can likely update to do the funnel prior to compiling the JS.

**Comment by rwjblue** [comment]
Ya, I did some `stew.debug`ing and the tree we pass to `DependencyFunnel` is transpiled down to AMD already.

**Comment by nathanhammond** [comment]
> Regardless, we can likely update to do the funnel prior to compiling the JS.

... I believe that this only works for things within the engine's namespace. In my mind (I blinked and missed the exact Babel changes) if the lazy engine's `routes.js` file depends on an asset which is imported from an addon I think we're back to having a bad day with AMD again.

**Comment by rwjblue** [comment]
@nathanhammond - Confirm, I believe that is definitely broken at the moment (in addition to "simple" relative imports from within the same addon).

**Comment by nathanhammond** [comment]
Linking together: https://github.com/ember-cli/ember-cli/pull/6530

**Comment by trentmwillis** [comment]
Ah, hadn't considered the addon import case.

It's seem like we would either want to deal completely with ES6 files or completely AMD files. The former is more desirable, but likely not possible without a significant amount of work upstream in Ember-CLI (or at least that's the impression I get). The latter seems to be what we currently have, but we don't have an easy way to grab the dependency graph.

There are Rollup plugins we could use to turn the AMD modules back into ES6 modules, but that seems like it would be a less than ideal solution. Current best shot would seem to be using an AMD dependency graph resolver; some quick searching, however, suggests there may not be a good one with a programmatic API.

**Comment by nathanhammond** [comment]
> significant amount of work upstream in Ember-CLI

All of that was added in https://github.com/ember-cli/ember-cli/pull/6530 and its followups. Given that, "what we currently have" only exists on `master` for Ember CLI and in no releases. It's possible to unwind (though it's not a simple revert at this point).

Current state has a number of limitations:
- The dependency graph becomes significantly more difficult to generate since we can't use standard ES6 tooling.
- I'd much rather trade performance for correctness, though it's possible that not doing double-transpile will cost us in performance for how we have to trace through things.
- There is at least one common addon relying on the existing behavior (`ember-engines`) but it's easy to believe that there are more addons which expect only ES6 modules since that was indeed the previous state. (Actually, my own ember-route-recognizer relies on it as well when used as an addon. Meaning that just I have written two things which relied on this.)
- Keeping everything in ES6 will make it _much_ easier in the future to deliver things such as linker/packager work. We may paint ourselves into an unfortunate corner by AMD-ifying early.

I've thought about this much of the day and I feel pretty sure that leaving things as modules as long as possible is our ideal.

Regardless, my kingdom for more and better testing tools, we really _truly_ need those as we get into modifying `lib/broccoli/ember-app` and `lib/models/addon`.

**Comment by stefanpenner** [comment]
https://github.com/ember-engines/broccoli-dependency-funnel/pull/18 should help enable

**Comment by rwjblue** [comment]
Fixed by https://github.com/ember-engines/broccoli-dependency-funnel/pull/18.
