### ISSUE TITLE
Support for scoped/organizational engines => mount('@org/engine')

### ISSUE THREAD

**Issue by gossi** [ember-engines/ember-engines#524]
So, I tried to create a scoped engine `@org/engine` and tried mounting it in the dummy app:

```
Router.map(function () {
  this.mount('@org/engine, { path: '/foo'});
});
```

which gives this error: `Assertion Failed: Asset manifest does not list any available bundles.`

I traced it down to this line: https://github.com/ember-engines/ember-asset-loader/blob/f8f1a448456697dbf128da27a15ca034d848763a/addon/services/asset-loader.js#L230

Second, here is the function that invokes the one above: https://github.com/ember-engines/ember-engines/blob/93f40763e22e536437a8fa63c66840ff9fa7b20d/addon/-private/router-ext.js#L238

**Comment by gossi** [comment]
Oh @lennyburdette hit me up on slack, he already did a PR to support this. See ember-engines/ember-asset-loader#63

**Comment by dfreeman** [comment]
Other than publishing a release of `ember-asset-loader` that has that fix in it, is there anything else blocking the use of engines with scoped names?

**Comment by lennyburdette** [comment]
So it turns out that fixing ember-asset-loader was only step 1. I didn't test out subroutes.

I believe the problem is that the engine is trying to look up its route map through the resolver with the key `route-map:@scope/pkg-name`. The `@` sigil already has some meaning in the classic resolver so it's being stripped away ([see relevant tests here][tests]). It ends up calling `require('scope/pkg-name/routes')` instead.

@rwjblue Do you think it's worth it to extend the classic resolver to handle `route-map:@scope/pkg-name` correctly? Or will it add more confusion because of the other uses of `@`?

[tests]:https://github.com/ember-cli/ember-resolver/blob/master/tests/unit/resolvers/classic/basic-test.js#L97-L146

**Comment by gossi** [comment]
Any progress here?

**Comment by rwjblue** [comment]
> @rwjblue Do you think it's worth it to extend the classic resolver to handle route-map:@scope/pkg-name correctly? Or will it add more confusion because of the other uses of @?

@lennyburdette - We can probably teach the resolver specifically about `:@`, which should unblock us here...

**Comment by buschtoens** [comment]
https://github.com/ember-cli/ember-resolver/blob/master/addon/resolvers/classic/index.js#L46-L75

Seems like there's already an exception for `helper:@content-helper`. Would the valid fix be just allowing any `fullName` containing `:@`?

**Comment by jherdman** [comment]
Is this resolved now? https://github.com/ember-cli/ember-resolver/pull/330 suggests as much.

**Comment by villander** [comment]
@buschtoens it's https://github.com/ember-cli/ember-resolver/pull/330 resolved your problem with scope? ca we close this issue?

**Comment by buschtoens** [comment]
Yes, it did. :)

**Comment by villander** [comment]
@rwjblue it's already fixed, can you close this, please?

**Comment by buschtoens** [comment]
It pretty much just works like with non-scoped engines.

```js
// router.js
this.mount('@my-org/my-engine', {
  path: 'foo',
  as: 'foo'
});
```

```js
// app.js
const App = Application.extend({
  // ...
  engines: {
    '@myOrg/myEngine': {
      dependencies: {
        services: [ /* ... */ ],
        externalRoutes: { /* ... */ }
      }
    }
  }
});
```

**Comment by villander** [comment]
@gossi this issue was solved for you as well

**Comment by gossi** [comment]
Pretty sure it does 👍

**Comment by villander** [comment]
@gossi can you close this issue, please? I don't privilege to do it
