### ISSUE TITLE
Remove ableist language from code generation

### ISSUE THREAD

**Issue by justintmckibben** [ember-engines/ember-engines#721]
Specifically referring to the usage of "dummy". Many people within the dev community are trying to improve language used within software to be more inclusive. Things such as master/slave, dummy, FactoryGirl, etc.

Here is Google's documentation on ableist language as a reference: https://developers.google.com/style/inclusive-documentation#ableist-language

It seems like a small change that can avoid offending someone or belittling a group of people.

**Comment by rwjblue** [comment]
Hmm, I'm not really sure about this one. I'm not completely opposed to changing to a different name (though it is not obvious that usage of the word "dummy" in this context is actually negative / ableist), but it needs to be done at a different level (e.g. ember-engines isn't really the thing that decides this name).

**Comment by justintmckibben** [comment]
What level would be the right level / where should I file this issue?

**Comment by rwjblue** [comment]
The change would have to be made in ember-cli itself, as ember-engines (and its blueprint) is mirroring the standard app name. I'm not sure if this would warrant an RFC (in emberjs/rfcs), but seems like it might. It certainly would affect all ember-cli addon developers (guides, docs, etc included), which might suggest that it should be an RFC discussion... 🤔

**Comment by stefanpenner** [comment]
Closing, not because "dummy" shouldn't be improved, but that such a change will require the above mentioned process, and this isn't the right issue tracker for this.

http://github.com/ember-cli/rfcs is most likely the best venue, and here is a similar RFC https://github.com/emberjs/rfcs/pull/639 that will serve as a great reference for what is expected for changing the `dummy` name.
