### ISSUE TITLE
queryparams return boolean value as string

### ISSUE THREAD

**Issue by sabarivelanganesan** [ember-engines/ember-engines#733]
Hi, 
When I use query params value as boolean it returns value as string("true" or "false") instead of(true or false).

Example: 
controller/box.js
`export default Controller.extend({`
  ` queryParams : ['canOpen'],`
   `canOpen: false`
`});`

template/box.hbs
`{{#if canOpen}}`
`This block will happen`
`{{/if}}`. 

In the functionalty, I mentioned above. We are getting **canOpen**  variable as string instead of boolean. So the condition doesn't get executed properly.

Does anyone know about this situation.

**Comment by villander** [comment]
@sabarivelanganesan could you please provide some reproduction in a public repo?

**Comment by bertdeblock** [comment]
@sabarivelanganesan What ember.js version are you using?

[This old ember.js issue](https://github.com/emberjs/ember.js/issues/4570) seems related. [Someone mentions the same behaviour](https://github.com/emberjs/ember.js/issues/4570#issuecomment-38331663). Unless we get an up-to-date reproduction, I think we can close this issue since the other issue is closed as well?
