### ISSUE TITLE
Pod style with tailwind inside in-repo engine doesn't processed correctly

### ISSUE THREAD

**Issue by taltcher** [ember-engines/ember-engines#763]
Hi, I'm having an issue when trying to use tailwindcss inside an in-repo engine. I have tailwindcss package installed in my main application - but when trying to write custom SCSS files inside my in-repo engine - using tailwindcss classes, for example:
```
.custom-class {
   @apply p-0;
}
```
As part of the build process, it takes that SCSS as is so it doesn't actually work. Is there a way to make it work without installing tailwindcss package in the in-repo engine as well?

**Comment by villander** [comment]
@taltcher could you please provide a minimal reproduction in a public repo?

**Comment by bertdeblock** [comment]
Any reason why you don't want to install `tailwindcss` as a dependency of the engine? If it uses `tailwindcss`, then it needs `tailwindcss` to be installed plus the corresponding setup I would think. The same would apply to a normal addon, so I don't think this issue is related to `ember-engines` as well.

**Comment by bertdeblock** [comment]
@taltcher is this still an issue for you? Can you close if otherwise?
