### ISSUE TITLE
Could not find module `@ember/legacy-built-in-components`

### ISSUE THREAD

**Issue by amiarSlimane** [ember-engines/ember-engines#814]
i have created a new project using ember 4.4.0, and  i have installed  ember-engines , trying to run the app i get the following error :  `Uncaught Error: Could not find module @ember/legacy-built-in-components imported from (require)`

**Comment by ginomiglio** [comment]
Looks like this is a result of https://github.com/ember-engines/ember-engines/pull/798:

>Note: engines authors may need to install @ember/legacy-built-in-components by themselves to have Ember 4 compatibility.
This PR introduced mechanism to use @ember/legacy-built-in-components when installed but it does not list @ember/legacy-built-in-components in dependencies hence that addon does not get installed automatically.

IMO the phrase `This PR introduced mechanism to use @ember/legacy-built-in-components when installed but it does not list @ember/legacy-built-in-components in dependencies` seems fundamentally incorrect, but hopefully it will be fixed by https://github.com/ember-engines/ember-engines/pull/810 I suppose.

**Comment by amiarSlimane** [comment]
Thank you , it is working now by adding this dependency .
